feat(api): account sign up
rodentskie/graphql_hov_be_onboarding pull request #1
Opened 2021-08-11 03:33 UTC by rodentskie

2021-08-11 05:43 UTC, kugtong33 requested changes

2021-08-11 05:43 UTC, kugtong33 commented on src/resolvers/account/index.ts
> +interface SignUpInput {
use `types` for plain object definitions, also separate this type into a different folder called `types`

2021-08-11 06:56 UTC, kugtong33 approved these changes

2021-08-12 01:12 UTC, merged

2021-08-12 01:13 UTC, ccpacillos approved these changes